/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tareadepoo;

import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import utilidades.TodoSql;

/**
 *
 * @author USUARIO
 */
public class DbSql extends javax.swing.JPanel {

    JDialog padreDialog;
    Principal principal;
    //-------------
    //SQL INFO
    //------------
    String servidor;
    String nombre;
    String contra;
    public void setSql(String servidor, String nombre, String contra){
        this.servidor = servidor;
        this.nombre = nombre;
        this.contra = contra;
    }
    //------------
    public DbSql(JDialog padreDialog, Principal principal) {
        initComponents();
        this.padreDialog = padreDialog;
        this.principal = principal;
        comboDataBase.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        radCrear = new javax.swing.JRadioButton();
        radElegir = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        comboDataBase = new javax.swing.JComboBox<>();
        txtBase = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Base de datos SQL");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 23, -1, -1));

        buttonGroup1.add(radCrear);
        radCrear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radCrear.setSelected(true);
        radCrear.setText("Crear");
        radCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCrearActionPerformed(evt);
            }
        });
        add(radCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 66, -1, -1));

        buttonGroup1.add(radElegir);
        radElegir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radElegir.setText("Elegir");
        radElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radElegirActionPerformed(evt);
            }
        });
        add(radElegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 66, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Establecer base de datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 241, -1));

        comboDataBase.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(comboDataBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 241, 40));

        txtBase.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(txtBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 241, 40));

        labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNombre.setText("Nombre:");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        padreDialog.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (radCrear.isSelected()) {
            if (txtBase.equals("")) {
                JOptionPane.showMessageDialog(this, "Dale un nombre a la base de datos");
                return;
            }
            crearDatabase();
        }else{
            String database = (String) comboDataBase.getSelectedItem();
            comprobarDatabase(database);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void comprobarDatabase(String database){
        if (TodoSql.tablasExisten(servidor, database, nombre, contra)) {
            principal.setBaseDeDatos(database);
            JOptionPane.showMessageDialog(this, "Base de datos seleccionada correctamente");
            padreDialog.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Elige una base de datos que tenga las tablas Alumnos y Docentes");
        }
    }
    private void crearDatabase(){
        if(TodoSql.crearDatabase(servidor, nombre, contra, txtBase.getText())){
            principal.setBaseDeDatos(txtBase.getText());
            JOptionPane.showMessageDialog(this, "Base de datos creada correctamente");
            padreDialog.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo crear la base de datos");
        }
    }
    private void radCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCrearActionPerformed
        if (radCrear.isSelected()) {
            comboDataBase.setVisible(false);
            labelNombre.setVisible(true);
            txtBase.setVisible(true);
            
        }
    }//GEN-LAST:event_radCrearActionPerformed

    private void radElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radElegirActionPerformed
        if (radElegir.isSelected()) {
            comboDataBase.setVisible(true);
            labelNombre.setVisible(false);
            txtBase.setVisible(false);
        }
        comboDataBase.removeAllItems();
        List<String> bases = TodoSql.listaDatabases(servidor, nombre, contra);
        for(String base : bases){
            if(!(base.equals("master") || base.equals("tempdb") || base.equals("model") || base.equals("msdb"))){
                comboDataBase.addItem(base);
            }
        }
    }//GEN-LAST:event_radElegirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboDataBase;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JRadioButton radCrear;
    private javax.swing.JRadioButton radElegir;
    private javax.swing.JTextField txtBase;
    // End of variables declaration//GEN-END:variables
}
