/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tareadepoo;

import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import utilidades.TodoSql;

/**
 *
 * @author USUARIO
 */
public class DbSql extends javax.swing.JPanel {

    JDialog padreDialog;
    Principal principal;
    //-------------
    //SQL INFO
    //------------
    String servidor;
    String nombre;
    String contra;
    public void setSql(String servidor, String nombre, String contra){
        this.servidor = servidor;
        this.nombre = nombre;
        this.contra = contra;
    }
    //------------
    public DbSql(JDialog padreDialog, Principal principal) {
        initComponents();
        this.padreDialog = padreDialog;
        this.principal = principal;
        comboDataBase.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        radCrear = new javax.swing.JRadioButton();
        radElegir = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        comboDataBase = new javax.swing.JComboBox<>();

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Base de datos SQL");

        buttonGroup1.add(radCrear);
        radCrear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radCrear.setSelected(true);
        radCrear.setText("Crear");
        radCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCrearActionPerformed(evt);
            }
        });

        buttonGroup1.add(radElegir);
        radElegir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radElegir.setText("Elegir");
        radElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radElegirActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Establecer base de datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboDataBase.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radCrear)
                                        .addGap(111, 111, 111)
                                        .addComponent(radElegir))
                                    .addComponent(comboDataBase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 117, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radCrear)
                    .addComponent(radElegir))
                .addGap(33, 33, 33)
                .addComponent(comboDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        padreDialog.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (radCrear.isSelected()) {
            
        }else{
            principal.setBaseDeDatos((String) comboDataBase.getSelectedItem());
            JOptionPane.showMessageDialog(this, "Base de datos seleccionada correctamente");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void radCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCrearActionPerformed
        if (radCrear.isSelected()) {
            comboDataBase.setVisible(false);
        }
    }//GEN-LAST:event_radCrearActionPerformed

    private void radElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radElegirActionPerformed
        if (radElegir.isSelected()) {
            comboDataBase.setVisible(true);
        }
        comboDataBase.removeAllItems();
        List<String> bases = TodoSql.listaDatabases(servidor, nombre, contra);
        for(String base : bases){
            if(!(base.equals("master") || base.equals("tempdb") || base.equals("model") || base.equals("msdb"))){
                comboDataBase.addItem(base);
            }
        }
    }//GEN-LAST:event_radElegirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboDataBase;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton radCrear;
    private javax.swing.JRadioButton radElegir;
    // End of variables declaration//GEN-END:variables
}
