/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareadepoo;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Listado extends javax.swing.JFrame {

    private Principal principal;
    
    public void setPrincipal(Principal principal){
        this.principal = principal;
    }
    
    DefaultTableModel modelo;
            
    /**
     * Creates new form Listado
     */
    public Listado() {
        initComponents();
        modelo = (DefaultTableModel) tablaAlum.getModel();
        modelo.addRow(new Object[]{1, "Ana", 20});
        modelo.addRow(new Object[]{2, "Luis", 22});
        jScrollPane2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlum = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDoc = new javax.swing.JTable();
        radAlum = new javax.swing.JRadioButton();
        radDocen = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Listado de personas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 223, -1));

        tablaAlum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Apellidos y nombres", "Fecha de nacimiento", "Telefono", "Direccion", "Sexo"
            }
        ));
        jScrollPane1.setViewportView(tablaAlum);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 810, 240));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 640, -1, -1));

        tablaDoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Apellidos y nombres", "Fecha de nacimiento", "Telefono", "Direccion", "Sexo", "Profesion"
            }
        ));
        jScrollPane2.setViewportView(tablaDoc);
        if (tablaDoc.getColumnModel().getColumnCount() > 0) {
            tablaDoc.getColumnModel().getColumn(6).setHeaderValue("Profesion");
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 810, 240));

        buttonGroup1.add(radAlum);
        radAlum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radAlum.setSelected(true);
        radAlum.setText("Alumno");
        radAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAlumActionPerformed(evt);
            }
        });
        getContentPane().add(radAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        buttonGroup1.add(radDocen);
        radDocen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radDocen.setText("Docente");
        radDocen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDocenActionPerformed(evt);
            }
        });
        getContentPane().add(radDocen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        modelo.setRowCount(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void radAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAlumActionPerformed
        if (radAlum.isSelected()) {
            jScrollPane2.setVisible(false);
            jScrollPane1.setVisible(true);
        }
    }//GEN-LAST:event_radAlumActionPerformed

    private void radDocenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDocenActionPerformed
        if (radDocen.isSelected()) {
            jScrollPane1.setVisible(false);
            jScrollPane2.setVisible(true);
        }
    }//GEN-LAST:event_radDocenActionPerformed
    private void rellenarTabla(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radAlum;
    private javax.swing.JRadioButton radDocen;
    private javax.swing.JTable tablaAlum;
    private javax.swing.JTable tablaDoc;
    // End of variables declaration//GEN-END:variables
}
