/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareadepoo;

import utilidades.Validar;
import utilidades.ArchivoJson;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import personal.Alumno;
import personal.Docente;
import utilidades.SqlDatos;
import utilidades.TodoSql;

/**
 *
 * @author USUARIO
 */
public class Modificar extends javax.swing.JFrame {
    
    private Principal principal;
    
    public void setPrincipal(Principal principal){
        this.principal = principal;
    }
    
    File archivo;
    
    public void setArchivo(File archivo){
        this.archivo = archivo;
    }
    
    private String tipo;
    public void setTipo(String tipo){
        this.tipo = tipo;
    }
    private SqlDatos datos;
    public void setDatos(SqlDatos datos){
        this.datos = datos;
    }
    List<Alumno> listaAlum;
    List<Docente> listaDoc;
    boolean cargado=false;
    public void establecerAlum(){
        radDocen.setSelected(false);
        radAlum.setSelected(true);
        labelProf.setVisible(false);
        txtProf.setVisible(false);
    }
    
    public Modificar() {
        initComponents();
        this.setLocationRelativeTo(null);
        labelProf.setVisible(false);
        txtProf.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        radAlum = new javax.swing.JRadioButton();
        radDocen = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        combDni = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNomApe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNacim = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelef = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDirec = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        combSex = new javax.swing.JComboBox<>();
        labelProf = new javax.swing.JLabel();
        txtProf = new javax.swing.JTextField();
        btnMod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(radAlum);
        radAlum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radAlum.setSelected(true);
        radAlum.setText("Alumno");
        radAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAlumActionPerformed(evt);
            }
        });

        buttonGroup1.add(radDocen);
        radDocen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radDocen.setText("Docente");
        radDocen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDocenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Modificar");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("DNI:");

        combDni.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        combDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combDniActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Apellidos y nombres:");

        txtNomApe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Fecha de nacimiento:");

        txtNacim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Telefono:");

        txtTelef.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Dirección:");

        txtDirec.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Sexo:");

        combSex.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        combSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "Otro" }));
        combSex.setToolTipText("");
        combSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combSexActionPerformed(evt);
            }
        });

        labelProf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelProf.setText("Profesion:");

        txtProf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnMod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMod.setText("Modificar");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMod)
                        .addGap(215, 215, 215)
                        .addComponent(jButton2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(combDni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radAlum)
                        .addGap(44, 44, 44)
                        .addComponent(radDocen)))
                .addGap(244, 244, 244))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(38, 38, 38)
                        .addComponent(combSex, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addComponent(txtTelef, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24)
                        .addComponent(txtNacim, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(22, 22, 22)
                        .addComponent(txtNomApe, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(labelProf)
                .addGap(11, 11, 11)
                .addComponent(txtProf, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radAlum)
                    .addComponent(radDocen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtNomApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProf)
                    .addComponent(txtProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtNacim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtTelef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(combSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btnMod)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAlumActionPerformed
        if (radAlum.isSelected()) {
            labelProf.setVisible(false);
            txtProf.setVisible(false);
            rellenarDniAlumnos();
        }
    }//GEN-LAST:event_radAlumActionPerformed

    private void radDocenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDocenActionPerformed
        if (radDocen.isSelected()) {
            labelProf.setVisible(true);
            txtProf.setVisible(true);
            rellenarDniDocentes();
        }
    }//GEN-LAST:event_radDocenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void combSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combSexActionPerformed

    private void combDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combDniActionPerformed
        if (!cargado) {
            return;
        }
        int index = combDni.getSelectedIndex();
        if (radAlum.isSelected()) {
            Alumno alum = listaAlum.get(index);
            rellenarTodoAlumno(alum);
        }else{
            Docente doc = listaDoc.get(index);
            rellenarTodoDocente(doc);
        }
    }//GEN-LAST:event_combDniActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed

        String respuesta=erroresRespuesta();

        if (!(respuesta.equals(""))) {
            JOptionPane.showMessageDialog(this, respuesta);
        }else{
            if (radDocen.isSelected()) {
                Docente docente = new Docente((String)combDni.getSelectedItem(), txtNomApe.getText(), txtNacim.getText(), txtTelef.getText(), txtDirec.getText(), (String)combSex.getSelectedItem(), txtProf.getText());
                if (tipo.equals("Sql")) {
                    TodoSql.modificarDocente(datos, docente);
                }else{
                    ArchivoJson.actualizarDocente(archivo, docente);
                }
            }else{
                Alumno alumno = new Alumno((String)combDni.getSelectedItem(), txtNomApe.getText(), txtNacim.getText(), txtTelef.getText(), txtDirec.getText(), (String)combSex.getSelectedItem());
                if (tipo.equals("Sql")) {
                    TodoSql.modificarAlumno(datos, alumno);
                }else{
                    ArchivoJson.actualizarAlumno(archivo, alumno);
                }
            }
            JOptionPane.showMessageDialog(this, "Se modifcó correctamente");
            if(radDocen.isSelected()){
                rellenarDniDocentes();
            }else{
                rellenarDniAlumnos();
            }
        }
    }//GEN-LAST:event_btnModActionPerformed
    
    private String erroresRespuesta(){
        Validar valid = new Validar();
        String respuesta = "";
        respuesta += valid.validarApeNom(txtNomApe.getText());
        respuesta += valid.validarFecha(txtNacim.getText());
        respuesta += valid.validarTelefono(txtTelef.getText());
        respuesta += valid.validarDireccion(txtDirec.getText());
        if (radDocen.isSelected() && txtProf.getText().equals("")) {
            respuesta += "Error en la profesion";
        }
        return respuesta;
    }
    
    public void rellenarDniAlumnos(){
        cargado = false;
        combDni.removeAllItems();
        if (tipo.equals("Sql")) {
            listaAlum = TodoSql.obtenerAlumnos(datos);
        }else{
            listaAlum = ArchivoJson.leerAlumnos(archivo);
        }
        if (!listaAlum.isEmpty()) {
            Alumno primerAlum = listaAlum.get(0);
            rellenarTodoAlumno(primerAlum);
            for(Alumno alum : listaAlum){
                combDni.addItem(alum.getDni());
            }
        }else{
            limpiar();
        }
        cargado = true;
    }
    public void rellenarDniDocentes(){
        cargado = false;
        combDni.removeAllItems();
        if (tipo.equals("Sql")) {
            listaDoc = TodoSql.obtenerDocentes(datos);
        }else{
            listaDoc = ArchivoJson.leerDocentes(archivo);
        }
        if (!listaDoc.isEmpty()) {
            Docente primerDoc = listaDoc.get(0);
            rellenarTodoDocente(primerDoc);
            for(Docente doc : listaDoc){
                combDni.addItem(doc.getDni());
            }
        }else{
            limpiar();
        }
        cargado = true;
    }
    public void rellenarTodoAlumno(Alumno alum){
        limpiar();
        txtNomApe.setText(alum.getApeNom());
        txtNacim.setText(alum.getFechaNac());
        txtTelef.setText(alum.getTelef());
        txtDirec.setText(alum.getDireccion());
        combSex.setSelectedIndex(alum.getSexo().equals("Hombre") ? 0 : alum.getSexo().equals("Mujer") ? 1 : 2 );
    }
    public void rellenarTodoDocente(Docente doc){
        limpiar();
        txtNomApe.setText(doc.getApeNom());
        txtNacim.setText(doc.getFechaNac());
        txtTelef.setText(doc.getTelef());
        txtDirec.setText(doc.getDireccion());
        txtProf.setText(doc.getProfesion());
        combSex.setSelectedIndex(doc.getSexo().equals("Hombre") ? 0 : doc.getSexo().equals("Mujer") ? 1 : 2 );
    }
    
    public void limpiar(){
        txtNomApe.setText("");
        txtNacim.setText("");
        txtTelef.setText("");
        txtDirec.setText("");
        txtProf.setText("");
        combSex.setSelectedIndex(0);
    }
    
    public void actualizarComponente(){
        SwingUtilities.updateComponentTreeUI(this);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMod;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combDni;
    private javax.swing.JComboBox<String> combSex;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelProf;
    private javax.swing.JRadioButton radAlum;
    private javax.swing.JRadioButton radDocen;
    private javax.swing.JTextField txtDirec;
    private javax.swing.JTextField txtNacim;
    private javax.swing.JTextField txtNomApe;
    private javax.swing.JTextField txtProf;
    private javax.swing.JTextField txtTelef;
    // End of variables declaration//GEN-END:variables
}
