/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareadepoo;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import utilidades.SqlDatos;

/**
 *
 * @author USUARIO
 */
public class Principal extends javax.swing.JFrame {

    Registro regis = new Registro();
    Listado lista = new Listado();
    Modificar modi = new Modificar();
    Eliminar elimi = new Eliminar();
    
    //-----------------------------
    //CONFIGURACION SQL
    //-----------------------------
    boolean conexionSql = false;
    String servidorSql="";
    String nombreSql;
    String contraSql;
    String baseDeDatos="";
    boolean sqlHabilitado = false;
    //------------------------------
    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileSelect = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        btnRegis = new javax.swing.JButton();
        btnListado = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btnModo = new javax.swing.JButton();
        btnArchivo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE UNIVERSIDAD");

        btnRegis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegis.setText("Registrar Alumno/Docente");
        btnRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisActionPerformed(evt);
            }
        });

        btnListado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnListado.setText("Listado de Alumnos/Docentes");
        btnListado.setEnabled(false);
        btnListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 51, 51));
        jButton7.setText("SALIR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btnModo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sol.png"))); // NOI18N
        btnModo.setBorderPainted(false);
        btnModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModoActionPerformed(evt);
            }
        });

        btnArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/json.png"))); // NOI18N
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Modificar Alumno/Docente");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar Alumno/Docente");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        comboTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Json", "Sql" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tipo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnModo)
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1)
                        .addGap(0, 196, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnListado, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnArchivo)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(btnModo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14)
                                .addComponent(btnRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnArchivo)
                        .addGap(55, 55, 55)))
                .addComponent(btnListado, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisActionPerformed
        regis.setPrincipal(this);
        regis.setVisible(true);
        if (sqlHabilitado && comboTipo.getSelectedItem().equals("Sql")) {
            regis.setSqlDat(new SqlDatos(servidorSql, nombreSql, contraSql, baseDeDatos));
            regis.setTipo("Sql");
        }else{
            regis.setTipo("Json");
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnRegisActionPerformed

    private void btnListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoActionPerformed
        lista.setPrincipal(this);
        lista.setVisible(true);
        if (sqlHabilitado && comboTipo.getSelectedItem().equals("Sql")) {
            lista.rellenarAmbas(new SqlDatos(servidorSql, nombreSql, contraSql, baseDeDatos));
        }else{
            lista.rellenarAmbas(archivoSeleccionado);
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnListadoActionPerformed
   //---------------------------------------------
    //MODO OSCURO Y MODO CLARO
    //--------------------------------------------
    boolean dark = true;
    
    private void btnModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModoActionPerformed
        if (dark){
            try {
                UIManager.setLookAndFeel( new FlatIntelliJLaf() );
                btnModo.setIcon(new ImageIcon(getClass().getResource("/iconos/luna.png")));
                dark = false;
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                UIManager.setLookAndFeel( new FlatDarculaLaf() );
                btnModo.setIcon(new ImageIcon(getClass().getResource("/iconos/sol.png")));
                dark = true;
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        SwingUtilities.updateComponentTreeUI(this);
        SwingUtilities.updateComponentTreeUI(fileSelect);
        regis.actualizarComponente();
        lista.actualizarComponente();
        modi.actualizarComponente();
        elimi.actualizarComponente();
    }//GEN-LAST:event_btnModoActionPerformed
    
    //----------------------------------------------
    //ELEGIR UN ARCHIVO JSON O SQL
    //----------------------------------------------
    
    File archivoSeleccionado;
            
    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        if (comboTipo.getSelectedItem().equals("Json")) {
            fileSelect.setCurrentDirectory(new File(System.getProperty("user.dir")));
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos JSON (*.json)", "json");
            fileSelect.setFileFilter(filter);
            fileSelect.setMultiSelectionEnabled(false);

            int result = fileSelect.showOpenDialog(this);

            if (result == fileSelect.APPROVE_OPTION) {
                archivoSeleccionado = fileSelect.getSelectedFile();
                JOptionPane.showMessageDialog(this, "Archivo cargado");
                btnListado.setEnabled(true);
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo cargar el archivo");
            }
        }else{
            if (!conexionSql) {
                JDialog mostrarSql = new JDialog(this,"Informacion Sql",true);
                mostrarSql.add(new InfoSql(mostrarSql,this));
                mostrarSql.pack();
                mostrarSql.setLocationRelativeTo(this);
                mostrarSql.setVisible(true);
                if (servidorSql.equals("")) {
                   return;
                }
            }
            JDialog baseSql = new JDialog(this,"Configurar base de datos Sql",true);
            DbSql configBase = new DbSql(baseSql,this);
            configBase.setSql(servidorSql, nombreSql, contraSql);
            baseSql.add(configBase);
            baseSql.pack();
            baseSql.setLocationRelativeTo(this);
            baseSql.setVisible(true);
            if (baseDeDatos.equals("")) {
                return;
            }
            sqlHabilitado=true;
            btnRegis.setEnabled(true);
            btnListado.setEnabled(true);
            btnModificar.setEnabled(true);
            btnEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_btnArchivoActionPerformed
    public void setSql(String server, String nombre, String contra){
        this.servidorSql =server;
        this.nombreSql = nombre;
        this.contraSql = contra;
        this.conexionSql = true;
    }
    public void setBaseDeDatos(String base){
        this.baseDeDatos = base;
    }
    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modi.setPrincipal(this);
        modi.setVisible(true);
        if (sqlHabilitado && comboTipo.getSelectedItem().equals("Sql")) {
            modi.setTipo("Sql");
            modi.setDatos(new SqlDatos(servidorSql, nombreSql, contraSql, baseDeDatos ));
        }else{
            modi.setTipo("Json");
            modi.setArchivo(archivoSeleccionado);
        }
        modi.rellenarDniAlumnos();
        modi.establecerAlum();
        this.setVisible(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        elimi.setPrincipal(this);
        elimi.setVisible(true);
        if (sqlHabilitado && comboTipo.getSelectedItem().equals("Sql")) {
            elimi.setTipo("Sql");
            elimi.setDatos(new SqlDatos(servidorSql, nombreSql, contraSql, baseDeDatos ));
        }else{
            elimi.setTipo("Json");
            elimi.setArchivo(archivoSeleccionado);
        }
        elimi.rellenarDniAlumnos();
        elimi.establecerAlum();
        this.setVisible(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        if (comboTipo.getSelectedItem().equals("Sql")) {
            btnArchivo.setIcon(new ImageIcon(getClass().getResource("/iconos/iconoSql.png")));
            btnRegis.setEnabled(false);
            if (sqlHabilitado) {
                btnRegis.setEnabled(true);
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
            }
        }else{
            btnArchivo.setIcon(new ImageIcon(getClass().getResource("/iconos/json.png")));
            btnRegis.setEnabled(true);
            if (archivoSeleccionado != null) {
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
                btnListado.setEnabled(true);
            }
        }
    }//GEN-LAST:event_comboTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListado;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModo;
    private javax.swing.JButton btnRegis;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JFileChooser fileSelect;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
