/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareadepoo;

import utilidades.Validar;
import utilidades.ArchivoJson;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import personal.Alumno;
import personal.Docente;

/**
 *
 * @author USUARIO
 */
public class Registro extends javax.swing.JFrame {
    private Principal principal;
    
    public void setPrincipal(Principal principal){
        this.principal = principal;
    }
    
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel5.setVisible(false);
            txtProf.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fileSave = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radAlum = new javax.swing.JRadioButton();
        radDocen = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNacim = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelef = new javax.swing.JTextField();
        txtDirec = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        combSex = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtProf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtNomApe = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Registrar nuevo Alumno/Docente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 6, -1, 67));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tipo de Persona:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        buttonGroup1.add(radAlum);
        radAlum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radAlum.setSelected(true);
        radAlum.setText("Alumno");
        radAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAlumActionPerformed(evt);
            }
        });
        getContentPane().add(radAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        buttonGroup1.add(radDocen);
        radDocen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radDocen.setText("Docente");
        radDocen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDocenActionPerformed(evt);
            }
        });
        getContentPane().add(radDocen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("DNI:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        txtDni.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 138, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Apellidos y nombres:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Fecha de nacimiento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        txtNacim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtNacim, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 240, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Telefono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        txtTelef.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtTelef, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 240, -1));

        txtDirec.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 240, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Dirección:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Sexo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        combSex.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        combSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "Otro" }));
        combSex.setToolTipText("");
        combSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combSexActionPerformed(evt);
            }
        });
        getContentPane().add(combSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 138, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Profesion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        txtProf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 133, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        txtNomApe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtNomApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 240, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combSexActionPerformed

    private void radAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAlumActionPerformed
        if (radAlum.isSelected()) {
            jLabel5.setVisible(false);
            txtProf.setVisible(false);
        }
    }//GEN-LAST:event_radAlumActionPerformed

    private void radDocenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDocenActionPerformed
         if (radDocen.isSelected()) {
            jLabel5.setVisible(true);
            txtProf.setVisible(true);
        }
    }//GEN-LAST:event_radDocenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String respuesta=erroresRespuesta();
        
        if (!(respuesta.equals(""))) {
            JOptionPane.showMessageDialog(this, respuesta);
        }else{
            
            File archivo = selecGuardar();
            
            if (archivo == null){
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo");
                return;
            }
            
            if (radDocen.isSelected()) {
                Docente docente = new Docente(txtDni.getText(), txtNomApe.getText(), txtNacim.getText(), txtTelef.getText(), txtDirec.getText(), (String)combSex.getSelectedItem(), txtProf.getText());
                ArchivoJson.guardarJsonDocentes(archivo,docente);
                
            }else{
                
                Alumno alumno = new Alumno(txtDni.getText(), txtNomApe.getText(), txtNacim.getText(), txtTelef.getText(), txtDirec.getText(), (String)combSex.getSelectedItem());
                ArchivoJson.guardarJsonAlumnos(archivo,alumno);
                
            }
            
            JOptionPane.showMessageDialog(rootPane, "Se registro correctamente");
            limpiar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private String erroresRespuesta(){
        Validar valid = new Validar();
        String respuesta = "";
        respuesta += valid.validarDni(txtDni.getText());
        respuesta += valid.validarApeNom(txtNomApe.getText());
        respuesta += valid.validarFecha(txtNacim.getText());
        respuesta += valid.validarTelefono(txtTelef.getText());
        respuesta += valid.validarDireccion(txtDirec.getText());
        if (radDocen.isSelected() && txtProf.getText().equals("")) {
            respuesta += "Error en la profesion";
        }
        return respuesta;
    }
    
    private File selecGuardar(){
        File archivo;
         fileSave.setDialogTitle("Guardar archivo JSON");

        fileSave.setCurrentDirectory(new File(System.getProperty("user.dir")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos JSON (*.json)", "json");
        fileSave.setFileFilter(filter);

        int result = fileSave.showSaveDialog(this);

        if (result == fileSave.APPROVE_OPTION) {
            archivo = fileSave.getSelectedFile();
            if (!archivo.getName().toLowerCase().endsWith(".json")) {
                archivo = new File(archivo.getParentFile(), archivo.getName() + ".json");
            }
        }else{
            return null;
        }
        return archivo;
    }
    
    private void limpiar(){
        txtProf.setText("");
        txtNacim.setText("");
        txtTelef.setText("");
        txtDirec.setText("");
        txtDni.setText("");
        txtNomApe.setText("");
        combSex.setSelectedIndex(0);
    }
    
    public void actualizarComponente(){
        SwingUtilities.updateComponentTreeUI(this);
        SwingUtilities.updateComponentTreeUI(fileSave);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combSex;
    private javax.swing.JFileChooser fileSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton radAlum;
    private javax.swing.JRadioButton radDocen;
    private javax.swing.JTextField txtDirec;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNacim;
    private javax.swing.JTextField txtNomApe;
    private javax.swing.JTextField txtProf;
    private javax.swing.JTextField txtTelef;
    // End of variables declaration//GEN-END:variables
}
